### ISSUE TITLE
请问一下开发者，这个工具的意义在哪呀？

### ISSUE THREAD

**Issue by qklee-lz** [jstzwj/LaTeXDiff#1]
with open(args.out, 'w') as output_f:
        cmd = f"latexdiff {old_file.name} {new_file.name}"
        print(cmd)
        p = subprocess.Popen(cmd,
                            stdout=output_f,
                            stderr=sys.stdout)
        p.wait()

这和我直接cmd输入latexdiff有什么区别啊？

**Comment by jstzwj** [comment]
没有区别，自用，--flatten参数出问题情况下的work around。
